[build]
  # 构建命令
  command = "pnpm build"
  # 构建输出目录
  publish = "dist"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

# 重定向规则 - 支持 SPA 路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置 - 安全和性能优化
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 静态资源缓存优化
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML 文件缓存
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 预览部署设置
[context.deploy-preview]
  command = "pnpm build"

# 分支部署设置
[context.branch-deploy]
  command = "pnpm build"

# 开发环境设置
[context.dev]
  command = "pnpm dev"